[project]
name = "baby-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rahul Iyer", email = "rahulair@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
baby-pytorch = "baby_pytorch:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "pytest>=9.1.1",
    "torch>=2.13.0",
]
